export const theme = {
  colors: {
    primary: {
      50: 'rgb(var(--primary-50) / <alpha-value>)',
      100: 'rgb(var(--primary-100) / <alpha-value>)',
      200: 'rgb(var(--primary-200) / <alpha-value>)',
      300: 'rgb(var(--primary-300) / <alpha-value>)',
      400: 'rgb(var(--primary-400) / <alpha-value>)',
      500: 'rgb(var(--primary-500) / <alpha-value>)',
      600: 'rgb(var(--primary-600) / <alpha-value>)',
      700: 'rgb(var(--primary-700) / <alpha-value>)',
      800: 'rgb(var(--primary-800) / <alpha-value>)',
      900: 'rgb(var(--primary-900) / <alpha-value>)',
      950: 'rgb(var(--primary-950) / <alpha-value>)',
      DEFAULT: 'rgb(var(--primary-500) / <alpha-value>)',
    },
    secondary: {
      50: 'rgb(var(--secondary-50) / <alpha-value>)',
      100: 'rgb(var(--secondary-100) / <alpha-value>)',
      200: 'rgb(var(--secondary-200) / <alpha-value>)',
      300: 'rgb(var(--secondary-300) / <alpha-value>)',
      400: 'rgb(var(--secondary-400) / <alpha-value>)',
      500: 'rgb(var(--secondary-500) / <alpha-value>)',
      600: 'rgb(var(--secondary-600) / <alpha-value>)',
      700: 'rgb(var(--secondary-700) / <alpha-value>)',
      800: 'rgb(var(--secondary-800) / <alpha-value>)',
      900: 'rgb(var(--secondary-900) / <alpha-value>)',
      950: 'rgb(var(--secondary-950) / <alpha-value>)',
      DEFAULT: 'rgb(var(--secondary-500) / <alpha-value>)',
    },
    success: {
      50: 'rgb(var(--success-50) / <alpha-value>)',
      100: 'rgb(var(--success-100) / <alpha-value>)',
      200: 'rgb(var(--success-200) / <alpha-value>)',
      300: 'rgb(var(--success-300) / <alpha-value>)',
      400: 'rgb(var(--success-400) / <alpha-value>)',
      500: 'rgb(var(--success-500) / <alpha-value>)',
      600: 'rgb(var(--success-600) / <alpha-value>)',
      700: 'rgb(var(--success-700) / <alpha-value>)',
      800: 'rgb(var(--success-800) / <alpha-value>)',
      900: 'rgb(var(--success-900) / <alpha-value>)',
      DEFAULT: 'rgb(var(--success-500) / <alpha-value>)',
    },
    warning: {
      50: 'rgb(var(--warning-50) / <alpha-value>)',
      100: 'rgb(var(--warning-100) / <alpha-value>)',
      200: 'rgb(var(--warning-200) / <alpha-value>)',
      300: 'rgb(var(--warning-300) / <alpha-value>)',
      400: 'rgb(var(--warning-400) / <alpha-value>)',
      500: 'rgb(var(--warning-500) / <alpha-value>)',
      600: 'rgb(var(--warning-600) / <alpha-value>)',
      700: 'rgb(var(--warning-700) / <alpha-value>)',
      800: 'rgb(var(--warning-800) / <alpha-value>)',
      900: 'rgb(var(--warning-900) / <alpha-value>)',
      DEFAULT: 'rgb(var(--warning-500) / <alpha-value>)',
    },
    error: {
      50: 'rgb(var(--error-50) / <alpha-value>)',
      100: 'rgb(var(--error-100) / <alpha-value>)',
      200: 'rgb(var(--error-200) / <alpha-value>)',
      300: 'rgb(var(--error-300) / <alpha-value>)',
      400: 'rgb(var(--error-400) / <alpha-value>)',
      500: 'rgb(var(--error-500) / <alpha-value>)',
      600: 'rgb(var(--error-600) / <alpha-value>)',
      700: 'rgb(var(--error-700) / <alpha-value>)',
      800: 'rgb(var(--error-800) / <alpha-value>)',
      900: 'rgb(var(--error-900) / <alpha-value>)',
      DEFAULT: 'rgb(var(--error-500) / <alpha-value>)',
    },
    neutral: {
      50: 'rgb(var(--neutral-50) / <alpha-value>)',
      100: 'rgb(var(--neutral-100) / <alpha-value>)',
      200: 'rgb(var(--neutral-200) / <alpha-value>)',
      300: 'rgb(var(--neutral-300) / <alpha-value>)',
      400: 'rgb(var(--neutral-400) / <alpha-value>)',
      500: 'rgb(var(--neutral-500) / <alpha-value>)',
      600: 'rgb(var(--neutral-600) / <alpha-value>)',
      700: 'rgb(var(--neutral-700) / <alpha-value>)',
      800: 'rgb(var(--neutral-800) / <alpha-value>)',
      900: 'rgb(var(--neutral-900) / <alpha-value>)',
      950: 'rgb(var(--neutral-950) / <alpha-value>)',
    },
    background: 'rgb(var(--background) / <alpha-value>)',
    foreground: 'rgb(var(--foreground) / <alpha-value>)',
    card: {
      DEFAULT: 'rgb(var(--card) / <alpha-value>)',
      foreground: 'rgb(var(--card-foreground) / <alpha-value>)',
    },
    popover: {
      DEFAULT: 'rgb(var(--popover) / <alpha-value>)',
      foreground: 'rgb(var(--popover-foreground) / <alpha-value>)',
    },
    muted: {
      DEFAULT: 'rgb(var(--muted) / <alpha-value>)',
      foreground: 'rgb(var(--muted-foreground) / <alpha-value>)',
    },
    accent: {
      DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
      foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
    },
    destructive: {
      DEFAULT: 'rgb(var(--destructive) / <alpha-value>)',
      foreground: 'rgb(var(--destructive-foreground) / <alpha-value>)',
    },
    border: 'rgb(var(--border) / <alpha-value>)',
    input: 'rgb(var(--input) / <alpha-value>)',
    ring: 'rgb(var(--ring) / <alpha-value>)',
  },
  borderRadius: {
    sm: 'var(--radius-sm)',
    DEFAULT: 'var(--radius)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
  },
  fontFamily: {
    sans: 'var(--font-sans)',
    arabic: 'var(--font-arabic)',
    mono: 'var(--font-mono)',
  },
  boxShadow: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    DEFAULT: 'var(--shadow-md)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
  },
  zIndex: {
    dropdown: 'var(--z-dropdown)',
    sticky: 'var(--z-sticky)',
    fixed: 'var(--z-fixed)',
    'modal-backdrop': 'var(--z-modal-backdrop)',
    modal: 'var(--z-modal)',
    popover: 'var(--z-popover)',
    tooltip: 'var(--z-tooltip)',
  },
  animation: {
    'slide-in': 'slide-in 0.3s ease-out',
    'slide-out': 'slide-out 0.3s ease-out',
    'fade-in': 'fade-in 0.2s ease-out',
    'fade-out': 'fade-out 0.2s ease-out',
    'scale-in': 'scale-in 0.2s ease-out',
    'spin': 'spin 1s linear infinite',
  },
};

// Typography scales
export const typography = {
  fontSize: {
    xs: ['0.75rem', { lineHeight: '1rem' }],
    sm: ['0.875rem', { lineHeight: '1.25rem' }],
    base: ['1rem', { lineHeight: '1.5rem' }],
    lg: ['1.125rem', { lineHeight: '1.75rem' }],
    xl: ['1.25rem', { lineHeight: '1.75rem' }],
    '2xl': ['1.5rem', { lineHeight: '2rem' }],
    '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
    '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
    '5xl': ['3rem', { lineHeight: '1' }],
    '6xl': ['3.75rem', { lineHeight: '1' }],
    '7xl': ['4.5rem', { lineHeight: '1' }],
    '8xl': ['6rem', { lineHeight: '1' }],
    '9xl': ['8rem', { lineHeight: '1' }],
  },
  fontWeight: {
    thin: '100',
    extralight: '200',
    light: '300',
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
    black: '900',
  },
};

// Spacing scales
export const spacing = {
  px: '1px',
  0: '0px',
  0.5: '0.125rem',
  1: '0.25rem',
  1.5: '0.375rem',
  2: '0.5rem',
  2.5: '0.625rem',
  3: '0.75rem',
  3.5: '0.875rem',
  4: '1rem',
  5: '1.25rem',
  6: '1.5rem',
  7: '1.75rem',
  8: '2rem',
  9: '2.25rem',
  10: '2.5rem',
  11: '2.75rem',
  12: '3rem',
  14: '3.5rem',
  16: '4rem',
  20: '5rem',
  24: '6rem',
  28: '7rem',
  32: '8rem',
  36: '9rem',
  40: '10rem',
  44: '11rem',
  48: '12rem',
  52: '13rem',
  56: '14rem',
  60: '15rem',
  64: '16rem',
  72: '18rem',
  80: '20rem',
  96: '24rem',
};

// Breakpoints for responsive design
export const screens = {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
};

export default { theme, typography, spacing, screens };
